name: Validate Pull Request

on:
  pull_request:
    branches: [ "master" ]

jobs:
  builds:
    name: Builds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p output/Multiplayer && mv test.txt output/Multiplayer/test.txt
    - name: Upload Mod Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Multiplayer
        path: |
          output/